# Generated by Django 5.1.6 on 2025-02-23 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orientacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pavimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=150, null=True)),
                ('tensao_min', models.FloatField()),
                ('tensao_max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('limite_inferior_permitido', models.FloatField()),
                ('limite_superior_permitido', models.FloatField()),
                ('unidade', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('orientacao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='twodos.orientacao')),
                ('pavimento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='twodos.pavimento')),
            ],
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='twodos.sala')),
            ],
        ),
        migrations.CreateModel(
            name='SensorLogico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('sensor_fisico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twodos.sensorfisico')),
                ('tipo_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twodos.tiposensor')),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('sensor_logico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twodos.sensorlogico')),
            ],
        ),
        migrations.CreateModel(
            name='LeituraSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('leitura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='twodos.leitura')),
                ('sensor_logico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='twodos.sensorlogico')),
            ],
        ),
    ]
