# Generated by Django 5.1.6 on 2025-02-23 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twodos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='orientacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twodos.orientacao'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='pavimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twodos.pavimento'),
        ),
    ]
