# Generated by Django 5.1.6 on 2025-02-24 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twodos', '0002_alter_sala_orientacao_alter_sala_pavimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twodos.sala'),
        ),
        migrations.AlterField(
            model_name='leiturasensor',
            name='leitura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twodos.leitura'),
        ),
        migrations.AlterField(
            model_name='leiturasensor',
            name='sensor_logico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twodos.sensorlogico'),
        ),
    ]
