# Generated by Django 5.1.6 on 2025-02-25 19:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twodos', '0003_alter_leitura_sala_alter_leiturasensor_leitura_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leitura',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Leitura Ambiental', 'verbose_name_plural': 'Leituras Ambientais'},
        ),
        migrations.AlterModelOptions(
            name='leiturasensor',
            options={'ordering': ['leitura__data_hora'], 'verbose_name': 'Leitura de Sensor', 'verbose_name_plural': 'Leituras de Sensores'},
        ),
        migrations.AlterModelOptions(
            name='orientacao',
            options={'ordering': ['nome'], 'verbose_name': 'Orientação', 'verbose_name_plural': 'Orientações'},
        ),
        migrations.AlterModelOptions(
            name='parametro',
            options={'ordering': ['sensor_logico', 'nome'], 'verbose_name': 'Parâmetro de Operação', 'verbose_name_plural': 'Parâmetros de Operação'},
        ),
        migrations.AlterModelOptions(
            name='pavimento',
            options={'ordering': ['nome'], 'verbose_name': 'Pavimento', 'verbose_name_plural': 'Pavimentos'},
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={'ordering': ['pavimento__nome', 'nome'], 'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AlterModelOptions(
            name='sensorfisico',
            options={'ordering': ['nome'], 'verbose_name': 'Sensor Físico', 'verbose_name_plural': 'Sensores Físicos'},
        ),
        migrations.AlterModelOptions(
            name='sensorlogico',
            options={'ordering': ['sensor_fisico__nome', 'descricao'], 'verbose_name': 'Sensor Lógico', 'verbose_name_plural': 'Sensores Lógicos'},
        ),
        migrations.AlterModelOptions(
            name='tiposensor',
            options={'ordering': ['descricao'], 'verbose_name': 'Tipo de Sensor', 'verbose_name_plural': 'Tipos de Sensores'},
        ),
        migrations.AlterField(
            model_name='leitura',
            name='data_hora',
            field=models.DateTimeField(db_index=True, verbose_name='Data e Hora da Medição'),
        ),
        migrations.AlterField(
            model_name='leitura',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='twodos.sala', verbose_name='Local de Medição'),
        ),
        migrations.AlterField(
            model_name='leiturasensor',
            name='leitura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_sensores', to='twodos.leitura', verbose_name='Leitura Associada'),
        ),
        migrations.AlterField(
            model_name='leiturasensor',
            name='sensor_logico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_sensor', to='twodos.sensorlogico', verbose_name='Sensor'),
        ),
        migrations.AlterField(
            model_name='leiturasensor',
            name='valor',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(1000)], verbose_name='Valor Medido'),
        ),
        migrations.AlterField(
            model_name='orientacao',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Orientação Cardinal'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='nome',
            field=models.CharField(help_text='Nome do parâmetro de configuração', max_length=50, verbose_name='Parâmetro Monitorado'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='sensor_logico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='twodos.sensorlogico', verbose_name='Sensor Associado'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='valor',
            field=models.FloatField(help_text='Valor de referência para o parâmetro', verbose_name='Valor Configurado'),
        ),
        migrations.AlterField(
            model_name='pavimento',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome do Pavimento'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome da Sala'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='orientacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_orientacao', to='twodos.orientacao', verbose_name='Orientação Geográfica'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='pavimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_pavimento', to='twodos.pavimento', verbose_name='Pavimento Associado'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='sigla',
            field=models.CharField(max_length=10, unique=True, verbose_name='Sigla Identificadora'),
        ),
        migrations.AlterField(
            model_name='sensorfisico',
            name='descricao',
            field=models.TextField(blank=True, help_text='Especificações técnicas e características físicas', null=True, verbose_name='Descrição Técnica'),
        ),
        migrations.AlterField(
            model_name='sensorfisico',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do Sensor'),
        ),
        migrations.AlterField(
            model_name='sensorfisico',
            name='sigla',
            field=models.CharField(help_text='Código único de identificação do sensor', max_length=10, unique=True, verbose_name='Código do Sensor'),
        ),
        migrations.AlterField(
            model_name='sensorfisico',
            name='tensao_max',
            field=models.FloatField(help_text='Valor máximo de tensão elétrica em volts', verbose_name='Tensão Máxima (V)'),
        ),
        migrations.AlterField(
            model_name='sensorfisico',
            name='tensao_min',
            field=models.FloatField(help_text='Valor mínimo de tensão elétrica em volts', verbose_name='Tensão Mínima (V)'),
        ),
        migrations.AlterField(
            model_name='sensorlogico',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='sensorlogico',
            name='descricao',
            field=models.CharField(help_text='Nome lógico/nomeação do sensor no sistema', max_length=50, verbose_name='Identificação do Sensor'),
        ),
        migrations.AlterField(
            model_name='sensorlogico',
            name='sensor_fisico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores_logicos', to='twodos.sensorfisico', verbose_name='Hardware Associado'),
        ),
        migrations.AlterField(
            model_name='sensorlogico',
            name='tipo_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores_tipo', to='twodos.tiposensor', verbose_name='Configuração de Medição'),
        ),
        migrations.AlterField(
            model_name='tiposensor',
            name='descricao',
            field=models.CharField(help_text='Tipo de grandeza física medida', max_length=50, unique=True, verbose_name='Tipo de Medição'),
        ),
        migrations.AlterField(
            model_name='tiposensor',
            name='limite_inferior_permitido',
            field=models.FloatField(help_text='Valor mínimo aceitável para medição', verbose_name='Limite Inferior'),
        ),
        migrations.AlterField(
            model_name='tiposensor',
            name='limite_superior_permitido',
            field=models.FloatField(help_text='Valor máximo aceitável para medição', verbose_name='Limite Superior'),
        ),
        migrations.AlterField(
            model_name='tiposensor',
            name='unidade',
            field=models.CharField(choices=[('°C', 'Celsius'), ('%', 'Porcentagem'), ('V', 'Volts'), ('lux', 'Iluminância')], max_length=10, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterUniqueTogether(
            name='leiturasensor',
            unique_together={('sensor_logico', 'leitura')},
        ),
        migrations.AlterUniqueTogether(
            name='parametro',
            unique_together={('sensor_logico', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='sensorlogico',
            unique_together={('sensor_fisico', 'descricao')},
        ),
        migrations.AddIndex(
            model_name='leitura',
            index=models.Index(fields=['data_hora'], name='twodos_leit_data_ho_564ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='sala',
            index=models.Index(fields=['sigla'], name='twodos_sala_sigla_9237c7_idx'),
        ),
    ]
