# Generated by Django 5.1.6 on 2025-03-03 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twodos', '0004_alter_leitura_options_alter_leiturasensor_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leitura',
            new_name='leitura_data_ho_218951_idx',
            old_name='twodos_leit_data_ho_564ffe_idx',
        ),
        migrations.RenameIndex(
            model_name='sala',
            new_name='sala_sigla_84591b_idx',
            old_name='twodos_sala_sigla_9237c7_idx',
        ),
        migrations.AlterField(
            model_name='leitura',
            name='sala',
            field=models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='twodos.sala', verbose_name='Local de Medição'),
        ),
        migrations.AlterField(
            model_name='leiturasensor',
            name='leitura',
            field=models.ForeignKey(db_column='id_leitura', on_delete=django.db.models.deletion.CASCADE, related_name='leituras_sensores', to='twodos.leitura', verbose_name='Leitura Associada'),
        ),
        migrations.AlterField(
            model_name='leiturasensor',
            name='sensor_logico',
            field=models.ForeignKey(db_column='id_sensor_logico', on_delete=django.db.models.deletion.CASCADE, related_name='leituras_sensor', to='twodos.sensorlogico', verbose_name='Sensor'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='sensor_logico',
            field=models.ForeignKey(db_column='id_sensor_logico', on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='twodos.sensorlogico', verbose_name='Sensor Associado'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='orientacao',
            field=models.ForeignKey(db_column='id_orientacao', on_delete=django.db.models.deletion.CASCADE, related_name='salas_orientacao', to='twodos.orientacao', verbose_name='Orientação Geográfica'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='pavimento',
            field=models.ForeignKey(db_column='id_pavimento', on_delete=django.db.models.deletion.CASCADE, related_name='salas_pavimento', to='twodos.pavimento', verbose_name='Pavimento Associado'),
        ),
        migrations.AlterField(
            model_name='sensorlogico',
            name='sensor_fisico',
            field=models.ForeignKey(db_column='id_sensor_fisico', on_delete=django.db.models.deletion.CASCADE, related_name='sensores_logicos', to='twodos.sensorfisico', verbose_name='Hardware Associado'),
        ),
        migrations.AlterField(
            model_name='sensorlogico',
            name='tipo_sensor',
            field=models.ForeignKey(db_column='id_tipo_sensor', on_delete=django.db.models.deletion.CASCADE, related_name='sensores_tipo', to='twodos.tiposensor', verbose_name='Configuração de Medição'),
        ),
        migrations.AlterModelTable(
            name='leitura',
            table='leitura',
        ),
        migrations.AlterModelTable(
            name='leiturasensor',
            table='leitura_sensor',
        ),
        migrations.AlterModelTable(
            name='orientacao',
            table='orientacao',
        ),
        migrations.AlterModelTable(
            name='parametro',
            table='parametro',
        ),
        migrations.AlterModelTable(
            name='pavimento',
            table='pavimento',
        ),
        migrations.AlterModelTable(
            name='sala',
            table='sala',
        ),
        migrations.AlterModelTable(
            name='sensorfisico',
            table='sensor_fisico',
        ),
        migrations.AlterModelTable(
            name='sensorlogico',
            table='sensor_logico',
        ),
        migrations.AlterModelTable(
            name='tiposensor',
            table='tipo_sensor',
        ),
    ]
